--- #YAML:1.0
name:                     Template-Plugin-Lingua-EN-Numbers
version:                  0.01
abstract:                 TT2 interface to Lingua::EN::Numbers modules
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                           5.006
  Template:                       2.07
  Template::Plugin:               2.07
  Template::Stash:                2.07
  Lingua::EN::Numbers:            0
  Lingua::EN::Numbers::Years:     0
  Lingua::EN::Numbers::Ordinate:  0
recommends:
  Test::CPAN::Meta:               0
  Test::CPAN::Meta::JSON:         0
  Test::Pod:                      1.00
  Test::Pod::Coverage:            0.08
build_requires:
  IO::File:                       0
  Template::Test:                 2.07
  Test::More:                     0.70

provides:
  Template::Plugin::Lingua::EN::Numbers:
    file:     lib/Template/Plugin/Lingua/EN/Numbers.pm
    version:  0.01
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Template-Plugin-Lingua-EN-Numbers
  repository: http://github.com/barbie/template-plugin-lingua-en-numbers

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
